title:             Justin Vs Micheal B. Jordan Insirped Workout
email:             ju3tin@hotmail.co.uk
description:       It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward; how much you can take and keep moving forward. That's how winning is done!
author:            Justin Grierson
baseurl:           ""
url:               "https://jvmbjiw.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
